### ISSUE TITLE
Rancherize has vim as hard requirement

### ISSUE THREAD

**Issue by justb81** [ipunkt/rancherize#1]
```
./vendor/bin/rancherize rancher:access
sh: 1: vim: not found

```

Rancherize should respect the EDITOR environment variable if set.

**Comment by svensp** [comment]
EDITOR=testkommando ./vendor/bin/rancherize rancher:access
sh: 1: testkommando: not found

The command already respects the EDITOR environment variable.

**Comment by justb81** [comment]
sorry. my fault.
