### ISSUE TITLE
Add composer to rancherize docker Image

### ISSUE THREAD

**Issue by svensp** [ipunkt/rancherize#30]
The command `plugin:install` uses composer to install the requested Plugin. This fails when using the containerized version because composer is not included.

```
  RUN  'composer' 'require' '--dev' 'ipunkt/rancherize-publish-with-traefik:^1.0.2'
  ERR  sh: composer: not found
  ERR  
  RES  127 Command did not run successfully
```

Either add composer to the Image or start composer via `docker run composer-docker-image`

**Comment by justb81** [comment]
all plugins are / should be included in the docker-images composer.json - there is no need for `plugin:install`
