### ISSUE TITLE
Discussion: include configurations

### ISSUE THREAD

**Issue by svensp** [ipunkt/rancherize#44]
There are times when configuration is not necessarily project specific.
For example all our apps share similar scheduling rules. Instead of adding them for every project it would make more sense to store the rules in a single external json file and including them by url.
Example: `https://svn-server/svn/rancherize-configuration/scheduler.json`
```json
{
   "scheduler":{
             "tags": ["apps"],
            "should-not-tags": ["failover"]
  }
}
```

Implementation:
New event in GlobalConfiguration and ProjectConfiguration: `(global|project).configuration.loaded`. Passes the loaded configuration
New Serivce `IncludeConfigurationService` parses Configurables looking for the key `include-config` and reads the url within, then adds the configuration file found at the target at the same depth as the include-config option.
EventHandler which ties the two: IncludeEventHandler. registers on `(global|project).configuration.loaded` and invokes the IncludeConfigurationService on the configuration.

**Comment by rokde** [comment]
Yes. Sounds better.
