### ISSUE TITLE
Discussion: Make volumes writeable by default

### ISSUE THREAD

**Issue by piJoe** [ipunkt/rancherize#45]
Currently volumes aren't writeable by default. It should be the standard behaviour for any volume to be writeable.

**Comment by rokde** [comment]
Absolutely yes. Readonly volumes should be an exception.

**Comment by svensp** [comment]
This is not as easy as saying it should be writable. All volumes are writable by default but they belong to root. Nginx and PHP drop root rights down to the www-data user as it should be.

The nginx Image solves this for laravel by chowning the default storage pathes to www-data.www-data every time it starts.
This is not a problem when developing but in a production environments with large amounts of files it will slow down the start of the container unnecessarily. Technically it only has to happen once when the volume is created.
