### ISSUE TITLE
Rancher URL: Global Url

### ISSUE THREAD

**Issue by svensp** [ipunkt/rancherize#50]
It is currently not possible to use a global rancher url. Only environment specific urls are supported.

To discuss:
Is this unwanted? Global api users can still use the environment specific urls.
Using the global api url would mean it is necessary to specify the target environment at some other place, pulling the burden of management into rancherize.
Currently it is perfectly viable to create different `rancher` accounts in ~/.rancherize with the same user but a different api url - one per target environment.

**Comment by rokde** [comment]
I would appreciate that global url handling.

**Comment by justb81** [comment]
IMHO is the environment-api and especially the key for the specific environment a security feature and should not be changed.

**Comment by svensp** [comment]
It is already possible to use global keys with rancherize.
The only thing that would change is that instead of deciding the the environment with the api-url used it would have to be stored elsewhere:

```json
{
  "rancher":{
    "some-account":{
      "url":"http://rancher.example.com/",
     "environment":"default".
     "key":"KEY",
    "secret":"SECRET"
    }
  }
}
```

Pro:
- It becomes possible to access multiple environments with a single account in `.rancherize`
Cons:
- One more api request to map the environment name to id(probably neglible)
- It is already possible to use different accounts in different project environments(staging.rancher.account = "account_for_environment_A", production.rancher.account = "Account_for_environment_B")

The only use-case I can think of right now which would require this is if for some reasons a single deploy needed to deploy into multiple environments. This sounds like a flawed design in itself to me.
