### ISSUE TITLE
rancherize has no `version` command

### ISSUE THREAD

**Issue by rokde** [ipunkt/rancherize#51]
I can not lookup the rancherize version within the docker container thing.

I wanted to check "the environment init takes the composer.json for project name" fixed issue - this does not work right now. I have pulled to ipunktbs/rancherize image right before doing that. A few seconds ago (2017-09-18 08:00).

For re-opening the closed issue I would check the library version. But there is no way doing that right now.

**Comment by svensp** [comment]
I can't seem to find an easy way to do this automatically.

I see the following options:
1. have a pre-commit hook add the commit hash to a version.txt
2. Use a build system to create releases. For the docker image this is simple: add `git describe --tags > version.txt` in the Dockerfile. For the packgist use case we'd have to use our own system
3. Add a `release` script to the repository which is used to create releases. In addition to creating the release `tag` it also adds the tagname to `version.txt` and uploads the current directory as `binary` files of the release

Probably easiest to do Steps 2 and 3 combined, then add a command to echo the version from the version.txt in the same directory as the `rancherize` entrypoint script.

**Comment by rokde** [comment]
I think the master should have a version constant or the opening of the application has to have a version given as argument. And this has to be set before a tag has to be applied.
