### ISSUE TITLE
Initializing project leaves a readonly rancherize.json

### ISSUE THREAD

**Issue by rokde** [ipunkt/rancherize#52]
When you use the docker image for initializing a new project the created `rancherize.json` has owner and group of `root`. Without sudo I can not remove this file anyway.

**Comment by rokde** [comment]
I used the call within the scripts folder including the `USER_ID` and `GROUP_ID` thing.

**Comment by svensp** [comment]
See https://github.com/ipunkt/nginx/blob/master/start.sh for reference on how we currently handle the USER_ID and GROUP_ID

**Comment by rokde** [comment]
In the linked script is the GROUP_ID missing (i do not know if it exists on every os by default). There are only chown calls - this is not suitable within the shell script calling rancherize through docker.
