### ISSUE TITLE
MultipleActiveServicesException Exception unnecessary when using in-service upgrade

### ISSUE THREAD

**Issue by svensp** [ipunkt/rancherize#57]
Rancherize currently matches services by only checking if the start of the service name matches the service name. This is a legacy from the time using rolling upgrades because service names included the version number back then.

Proposed fix: Have the RancherService::getActiveServiceDefinition take a parameter whether to match the full name or the beginning. Set this according to whether in-service is set or not.

**Comment by svensp** [comment]
testable in branch in-service-name-matching

**Comment by svensp** [comment]
Docker branch image is built: `docker run -it -v $HOME/.rancherize:/home/rancherize/.rancherize -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):$(pwd) -w $(pwd) -e "USER_ID=$(id -u)" -e "GROUP_ID=$(id -g)"  ipunktbs/rancherize:in-service-name-matching push ENVIRONMENT VERSION`

**Comment by svensp** [comment]
Deploy tested - works.
EnvironmentVersionCommand switched to NameMatcher and in-service checking as well.
Took the opportunity to move those 2 commands from the app/lists/commands.php to a CommandsProvider which can do dependency injection for them, specifically the InServiceChecker.

Important:
Because the Push now only checks for the exact service it does no longer transition from rolling upgrade services(ServiceName-VERSIONNUMBER) to in-service Services(just ServiceName). It will instead create a new Service for in-service upgrade so the old service can be deleted.
Alternatively you could rename the rolling-upgrade service and remove the version number - probably preferable if a lot of containers link to it.

**Comment by rokde** [comment]
It works. So we can close that issue.

**Comment by svensp** [comment]
fixed in master. Will be in the next minor release
Kinda breaks backwards compatibility because the transition from rolling upgrade -> in service upgrade is no longer available but it does not seem sever enough to warrant a major.
