### ISSUE TITLE
Blueprint events

### ISSUE THREAD

**Issue by svensp** [ipunkt/rancherize#65]
Similar to #64 
The webserver blueprint is becoming huge with currently 557 lines. This is because we provide more and more services along with it and all of them have to be added inside the blueprint.

This is bad in a couple of ways:
- The blueprint does not have a single responsibility
- Each functionality is split inside the class between init, validate and build.
- New functionality has to be added inside the blueprint, violating the open-closed principle

Proposed change:
Have the WebserverBlueprint only build the nginx container with its data. All other functionality is added as sub modules. Modules register to events
- WebserverInitEvent
- WebserverInitDevEvent
- WerbserverInitProductionEvent
- WebserverValidateEvent
- WebserverBuildEvent

-> all code concerning adding php-fpm to the image is moved into a Php submodule within the WebserverBlueprint

**Comment by svensp** [comment]
Thoughts?

**Comment by rokde** [comment]
We should divide the Blueprint in smaller pieces. A Blueprint should delegate the settings/preparation to a "huge" library of service configuration classes. Think of each service defined in a docker-compose.yml on his own, linked together by their name.

**Comment by svensp** [comment]
This is already how code is organized although some refactoring is needed for the older code to adhere to it completely.
