### ISSUE TITLE
Improve validation

### ISSUE THREAD

**Issue by svensp** [ipunkt/rancherize#66]
currently validation is almost unused. This is among other things because validation errors are thrown as exceptions so it is only possible to show a single error per run and it is not possible to show warnings.
Another reason is that the provided Validator does not have many rules written for it yet.

Proposed changes:
Move validate from throwing Exceptions to a boolean return. Provider an `ErrorBag` object to the call which can take both warnings and errors.

**Comment by svensp** [comment]
Thoughts?

**Comment by rokde** [comment]
Input validation or what kind of validation?

**Comment by svensp** [comment]
Validation of the rancherize.json.
Example:
The PhpService should provide validation for
```php
{
  "environments":{
     "local":{
        "php":{
            "version":"7.0"
         }
     }
  }
}
```

Setting invalid values should throw errors. For example setting `php.version` to `10` would print an error and fail validation because the version is not available and without it the service cannot be built.
Setting unknown values should throw warnings. For example misspelling `version` as `vesion` should throw a warning because it is not a known key.
Reason: it is not an error because the rancherize.json could include data for future versions. The user should be told about it however because it could be a typo of a known key.

**Comment by rokde** [comment]
Each service should have its own validator and gets the whole config for validation. If it fails a ValidationExceptino with an ErrorBag gets thrown and has to be displayed to the user.
So every service validator has the whol configuration file to check dependent values. For example adding a queues array without having a redis service added should throw an error.
