### ISSUE TITLE
Move WebserverBlueprint to official nginx+php fpm

### ISSUE THREAD

**Issue by svensp** [ipunkt/rancherize#69]
https://github.com/ipunkt/nginx which is currently used by WebserverBlueprint currently brings 3 things together:
- nginx
- php-fpm 7.0
- nginx configuration
Going by the single responsibility principle this should not be done.
Instead an `ipunktbs/nginx-configuration` Image should be created containing the configuration files and rancherize should bring together the official nginx + php-fpm images with the configuration

**Comment by svensp** [comment]
The current nginx image includes several php extra modules.

Among others:
- zip
- mbstring
- predis

The image itself https://hub.docker.com/_/php/ recommends creating your own image with the necessary modules. Do we make our own php-fpm image or is there a `laravel` or `all modules` themed image we could incorporate?

**Comment by justb81** [comment]
make an own image using:
```
EXTENSIONS="…"
RUN docker-php-source extract \
    && docker-php-ext-install $EXTENSIONS \
    && docker-php-source delete
```

**Comment by rokde** [comment]
Or you just use laradock ready-tailored docker images: https://github.com/laradock/laradock/tree/master/php-fpm and https://github.com/laradock/laradock/tree/master/nginx and all the others
