### ISSUE TITLE
Allow to push to other docker registries 

### ISSUE THREAD

**Issue by justb81** [ipunkt/rancherize#72]
@svensp we need to push to other registries (e.g. gitlab)

**Comment by svensp** [comment]
This is already possible.
Add a `server` field to your docker account in `~/.rancherize` this will be passed to `docker login`
Pushing to it is done by specifying `HOSTDNS/user/repo` instead of just `user/repo` as `docker.repository` inside the project

**Comment by justb81** [comment]
TODO: Test image `ipunktbs/rancherize:justb81-docker-server` on gitlab

**Comment by justb81** [comment]
tested and merged
