### ISSUE TITLE
Cron scheduling: default seconds to 0

### ISSUE THREAD

**Issue by svensp** [ipunkt/rancherize#83]
Cron documentation correctly states that all options not given will be set to `*` however it also lists
```php
{
'hour' => 2,
'minute' => 30,
}
```
as running at 2:30 where it would actually run at 2:30:01, 2:30:02, 2:30:03... 2:30:59 (unless the container takes more than a minute to run)

Proposed solution:
Set `seconds` default value to `0`

**Comment by svensp** [comment]
Thoughts? This would break backwards compatibility if someone actually wants it to run their container every second of the given time.
I think this use case it more likely to be an accident thought

**Comment by justb81** [comment]
> Set `seconds` default value to `0`
in respect to the other options this should be `second`.
