### ISSUE TITLE
Adding the possibility to pull images before starting

### ISSUE THREAD

**Issue by rokde** [ipunkt/rancherize#88]

**Comment by svensp** [comment]
Added in Commit 7afda512f8d8b66fb1d6320c8a52c3a723ae7e8d

Defaults to always pull images on upgrades.
Can be changed for all services by setting `docker.always-pull: true|false` in either the environment to be built or in the defaults.
It is possible to set it in-code via `$service->setAlwaysPulled(Service::ALWAYS_PULLED_{DEFAULT,TRUE,FALSE})`

Only ALWAYS_PULLED_DEFAULT takes `docker.always-pull` into account.

**Comment by rokde** [comment]
Works fine with 2.23.0
