### ISSUE TITLE
php-commands with `is-service: true` missing volumes

### ISSUE THREAD

**Issue by piJoe** [ipunkt/rancherize#97]
We have a scheduled php-command that executes the import for a website.
Since we changed the behaviour to `is-service: true` the volumes from the main project, which we need for the importer to run, are no longer attached to the command.

The volumes as defined in the rancherize.json should also be attached to any `is-service: true` php-command or there needs to be a way to define volumes for those commands.

**Comment by svensp** [comment]
Should be fixed in 2.34.3, please test it and close this issue if it is.

**Comment by piJoe** [comment]
Works perfectly! Thanks.
